#source 'https://github.com/CocoaPods/Specs.git'
platform:ios,'9.0'
target 'CGXPageHomeScrollView-OC' do
  
  pod 'CGXPageHomeScrollViewOC', :path => '../'
  
  pod 'Masonry'
  pod 'MJRefresh'
  pod 'SDWebImage'
end

